name: Build and Release PDFs

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/build-release.yml
    - '**/*.typ'
    - Makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: typst-community/setup-typst@v4

    - name: Install fd
      run: |
        sudo apt-get update
        sudo apt-get install fd-find

    - name: Build Typst
      run: make compile

    - name: Rename PDFs with folder names
      run: make rename

    - name: List PDFs
      run: tree

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: |
          ./notes/**/**/*_notes.pdf
        tag_name: pdf-${{ github.sha }}
        name: PDF Build ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
